# DRAGON REAL ESTATE PRICE PREDICTOR

In [1]:
import pandas as pd

In [2]:
housing=pd.read_csv("data.csv")

In [3]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       501 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [5]:
housing['CHAS']

0      0
1      0
2      0
3      0
4      0
      ..
501    0
502    0
503    0
504    0
505    0
Name: CHAS, Length: 506, dtype: int64

In [6]:
housing['CHAS'].value_counts()

0    471
1     35
Name: CHAS, dtype: int64

In [7]:
housing.describe()



CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.285655   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.705637   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.884000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.209000   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.629000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [8]:
%matplotlib inline

In [9]:
# for plotting histogram
# import matplotlib.pyplot as plt
# housing.hist(bins=50 , figsize=(20 , 15))

## Train-Test Splitting

In [10]:

#  for leraning purpose 
import numpy as np
def split_train_test(data , test_ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(data))
    print(shuffled)
    test_set_size=int(len(data)*test_ratio)
    test_indices=shuffled[:test_set_size]
    train_indices=shuffled[test_set_size:]
    return data.iloc[train_indices] , data.iloc[test_indices]

In [11]:
# train_set , test_set = split_train_test(housing , 0.2) 

In [12]:
#print("Rows in testing data:" ,  {len(test_set)}, "\n" , "Rows in training data:" , {len(train_set)})

In [13]:
from sklearn.model_selection import train_test_split
train_set , test_set = train_test_split(housing , test_size=0.2 , random_state=42)
print("Rows in testing data:" ,  {len(test_set)}, "\n" , "Rows in training data:" , {len(train_set)})

Rows in testing data: {102} 
 Rows in training data: {404}


## Shuffling 

In [14]:
from sklearn.model_selection import StratifiedShuffleSplit
split=StratifiedShuffleSplit(n_splits=1 , test_size=0.2 , random_state=42)
for train_index , test_index in split.split(housing , housing['CHAS']):
    strat_train_set=housing.loc[train_index]
    strat_test_set=housing.loc[test_index]

In [66]:
strat_train_set['CHAS'].value_counts()

0    376
1     28
Name: CHAS, dtype: int64

In [16]:
strat_test_set['CHAS'].value_counts()

0    95
1     7
Name: CHAS, dtype: int64

In [17]:
housing = strat_train_set.copy() # Now onforward  we will work on the traning daa

In [18]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  399.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.281130   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.716857   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.876500   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.211000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.633000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  404.000000  404.000000  
mean    12.791609   22.509406  
std      7.235740    9.385531  
min      1.730000    5.000000  
25%      6.847500   16.600000  
50%     11.570000   21.150000  
75%     17.102500   25.000000  
max     36.980000   50.000000

## Looking for Co-relation

In [19]:
corr_matrix=housing.corr()
corr_matrix['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.680649
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [20]:
from pandas.plotting import scatter_matrix

In [21]:
attributes=["RM","LSTAT","MEDV","ZN"]

In [22]:
#scatter_matrix(housing[attributes] , figsize=(12, 8))

In [23]:
#housing.plot(kind='scatter' , x="RM" , y="MEDV" , alpha=0.8)

##  Trying Out Attribute Combinations

In [24]:
housing['TAXRM']=housing['TAX']/housing['RM']

In [25]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
254  0.04819  80.0   3.64     0  0.392  6.108  32.0  9.2203    1  315   
348  0.01501  80.0   2.01     0  0.435  6.635  29.7  8.3440    4  280   
476  4.87141   0.0  18.10     0  0.614  6.484  93.6  2.3053   24  666   
321  0.18159   0.0   7.38     0  0.493  6.376  54.3  4.5404    5  287   
326  0.30347   0.0   7.38     0  0.493  6.312  28.9  5.4159    5  287   

     PTRATIO       B  LSTAT  MEDV       TAXRM  
254     16.4  392.89   6.57  21.9   51.571709  
348     17.0  390.94   5.99  24.5   42.200452  
476     20.2  396.21  18.68  16.7  102.714374  
321     19.6  396.90   6.87  23.1   45.012547  
326     19.6  396.90   6.15  23.0   45.468948

In [26]:
corr_matrix=housing.corr()
corr_matrix['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.680649
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
TAXRM     -0.528703
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [27]:
#housing.plot(kind='scatter' , x="TAXRM" , y="MEDV" , alpha=0.8)

In [28]:
housing =strat_train_set.drop('MEDV' , axis =1)
housing_labels=strat_train_set['MEDV'].copy()
 # we have  to seperate attributes and labels before calling linear regression 

## Missing Attributes

In [29]:
# To Take care of missing attributes , you have three options:
#     1. Get rid of the missing data points
#     2. Get rid of the whole attribute
#     3. Set the value to some value(0, mean or median)

In [30]:
a=housing.dropna(subset=["RM"]).shape #OPTION 1
a
# Note that the orginal housing dataframe will remain unchanged

(399, 13)

In [31]:
housing.drop("RM" , axis=1).shape #option 2
# There is no RM column and also note that the orginal housing dataframe will remain unchanged

(404, 12)

In [32]:
median=housing["RM"].median() #Compute median for option 3

In [33]:
median

6.211

In [34]:
housing["RM"].fillna(median) #option 3
# Note that the orginal housing dataframe will remain unchanged

254    6.108
348    6.635
476    6.484
321    6.376
326    6.312
       ...  
155    6.152
423    6.103
98     7.820
455    6.525
216    5.888
Name: RM, Length: 404, dtype: float64

In [35]:
housing.shape  # it again becomes normal

(404, 13)

# now in this case the missing data was only in RM , but there might me missing data in any column in the dataset that we might not known 

so for that promblem we will use a imputer 

In [36]:
strat_test_set.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  102.000000  102.000000  102.000000  102.000000  102.000000  102.000000   
mean     3.655942   13.450980   10.312255    0.068627    0.541353    6.303353   
std     10.400966   27.503241    6.761154    0.254068    0.111397    0.662996   
min      0.009060    0.000000    0.460000    0.000000    0.385000    4.138000   
25%      0.057827    0.000000    4.950000    0.000000    0.448000    5.912750   
50%      0.176150    0.000000    7.760000    0.000000    0.515000    6.176000   
75%      2.061955    0.000000   18.100000    0.000000    0.612750    6.539500   
max     88.976200   90.000000   27.740000    1.000000    0.871000    8.725000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  102.000000  102.000000  102.000000  102.000000  102.000000  102.000000   
mean    66.733333    3.988460    8.813725  391.980392   18.385294  369.670196   
std     27.772183    2.131247    8.614667  167.837379    2.310604   68.075774   
min      6.500000    1.137000    1.000000  188.000000   12.600000    3.650000   
25%     45.850000    2.223650    4.000000  270.000000   16.800000  377.685000   
50%     71.100000    3.422950    5.000000  307.000000   19.150000  393.740000   
75%     93.500000    5.609225    8.000000  461.000000   20.200000  396.900000   
max    100.000000   10.585700   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  102.000000  102.000000  
mean    12.104314   22.625490  
std      6.759257    8.452344  
min      2.470000    5.000000  
25%      7.480000   18.925000  
50%     10.565000   21.500000  
75%     16.267500   25.000000  
max     37.970000   50.000000

In [37]:
housing.describe() #before we start the imputer  note that RM has 399 values

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  399.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.281130   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.716857   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.876500   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.211000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.633000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

In [38]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy="median")
imputer.fit(housing)

SimpleImputer(strategy='median')

In [39]:
imputer.statistics_

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.21100e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01])

In [40]:
X=imputer.transform(housing)

In [41]:
housing_tr=pd.DataFrame(X , columns=housing.columns)

In [42]:
housing_tr.describe()# you can see RM has count of 404

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.280262   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.712438   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.211000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630250   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

## Scikit learn design

Primarily , there are three types of objects :

 1.Estimators : it estimates some parameters based on a dataset.Eg Imputer.It has fix method and transform method.Fit Method-Fit the dataset and calculate the internal parameters   

2.Transformers- Transform method takes input and returns output based on learnings from fit().It also has convenience function called fit_transform() which fits and then transform 

3.Predictors-LinearRegression model is an example of Predictor. fit() and predict() are two common functions.It also gives score() function which will evalute the predictions  

## Features Scaling 

Primarily , Two types of Features Scaling methods-

1.Min-Max Scaling(Normalization):
  (value-min)/(max-min) - due to this all values comes bwt 0 and 1.
  Sklearn provides a class called MinMaxScaler for this 

2.Standardization: (value - mean) / std . Sklearn provides a class called Standard Scaler for this

## Creating a PipeLine

In [43]:
from sklearn.pipeline import Pipeline

In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
my_pipeline=Pipeline([
    ('imputer'  , SimpleImputer(strategy='median')),
    # ........ add as many as you can in your pipeline
    ('std_scaler' ,StandardScaler())
])

In [46]:
housing_num_tr=my_pipeline.fit_transform(housing)

In [47]:
housing_num_tr.shape


(404, 13)

## Select a desired model for dragon real estates

In [48]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
#model=DecisionTreeRegressor()
#model=LinearRegression()
model=RandomForestRegressor()
model.fit(housing_num_tr , housing_labels) # we have  to seperate attributes and labels before calling linear regression 


RandomForestRegressor()

In [49]:
some_data=housing.iloc[:5]

In [50]:
some_labels=housing_labels.iloc[:5]

In [51]:
prepared_data=my_pipeline.transform(some_data)

In [52]:
model.predict(prepared_data)

array([22.664, 25.673, 16.337, 23.512, 23.511])

In [53]:
list(some_labels)

[21.9, 24.5, 16.7, 23.1, 23.0]

##Lets evaluate the model and see the error bwteen our predictions and the actual labels , for which we will use mean square error from sklearn

In [54]:
from sklearn.metrics import mean_squared_error
housing_prediction=model.predict(housing_num_tr)
mse=mean_squared_error(housing_labels , housing_prediction)
rmse=np.sqrt(mse)

In [55]:
mse  # Dont be happy , your model just overfitted the traning data.....we have to make such a model which follows the trend not the noise .......

1.36128012871287




## Using Better Evalution techniques - Cross Validation

In [56]:
#eg : 1 2 3 4 5 6 7 8 9 10 we are making ten groups of the whole datapoints which we have......that why cv=10
from sklearn.model_selection import cross_val_score
scores=cross_val_score( model , housing_num_tr , housing_labels , scoring='neg_mean_squared_error' , cv=10)
rmse_scores=np.sqrt(-scores)

In [57]:
rmse_scores

array([2.8476804 , 2.79464071, 4.3749778 , 2.84789395, 3.60491301,
       2.70077195, 4.7501106 , 3.25437757, 3.18992213, 3.16248247])

In [58]:
def print_scores(scores):
    print("Scores : " , scores)
    print("Mean : " , scores.mean())
    print("Standard Deviation : " , scores.std())


In [59]:
print_scores(rmse_scores)

Scores :  [2.8476804  2.79464071 4.3749778  2.84789395 3.60491301 2.70077195
 4.7501106  3.25437757 3.18992213 3.16248247]
Mean :  3.3527770572851745
Standard Deviation :  0.6618217710548406


# # Mean and std of diff machine learning models
Model Outputs

1.DecisionTreeRegressor :
  Mean :  4.057173924418416
  Standard Deviation :  0.690233340322275

2.LinearRegression : 
  Mean :  5.028209826107714
  Standard Deviation :  1.0557508139315424

3.RandomForestRegressor:
  Mean :  3.3013117857890286
  Standard Deviation :  0.6344369004821381

## Saving the model 

In [60]:
from joblib import dump , load
dump(model , "Dragon.joblib")

['Dragon.joblib']

## Testing the model on test data

In [61]:
X_test=strat_test_set.drop("MEDV" , axis=1)
Y_test=strat_test_set["MEDV"].copy()
X_test_prepared=my_pipeline.transform(X_test)
final_predictions=model.predict(X_test_prepared)
final_mse=mean_squared_error(Y_test , final_predictions)
final_rmse=np.sqrt(final_mse)

In [62]:
final_rmse

2.9863022219434385

In [63]:
prepared_data[0]

array([-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.24209245, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034])

## Using the models

In [64]:
import numpy as np
from joblib import dump , load
model=load("Dragon.joblib")
features=np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.24209245, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])
model.predict(features)

array([22.664])